name: arc_progress_bar_new
description: Package that simplifies the creation of a curved or arc-shaped progress bar widget.
version: 1.0.4
homepage: https://github.com/Frankline-Sable/arc_progress_bar

environment:
  sdk: '>=3.0.5 <4.0.0'
  flutter: 

dependencies:
  flutter:
    sdk: flutter

  vector_math: ^2.1.4


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3

flutter:

